# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 284951c1b5f8e198afbe3c71f94fd0f26b596b8f60d6669a6d8b7b102c1d2efded0b56d315a969534c4e0d938bc6d2747a4edf7c1a107d9621ecf305ce740bdd

test:
  secret_key_base: a27880a208580442c19baf8f62e0fa92a0ce18796b9614c680036096192c61062360a4760ad5cfd3342d79e6e54054bb54a3a244770313e65b2bd26db0c75ebf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
